version: '3.8'

services:
  web:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:5003"
    volumes:
      - ./app:/app   # Tüm app ve içindeki certs dizini dahil mount ediliyor
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

networks:
  default:
    driver: bridge
