events {
    worker_connections 1024;
}

    http {
        # Hata logları için opsiyonel
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

    server {
        listen 80;
        server_name pelinustunel.store www.pelinustunel.store;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name pelinustunel.store www.pelinustunel.store;

        ssl_certificate /etc/letsencrypt/live/pelinustunel.store/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pelinustunel.store/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            proxy_pass http://localhost:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}